---
title: "PNAD"
output: html_document
---

```{r, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

A PNAD, Pesquisa Nacional por Amostra de Domicílios, é uma pesquisa realizada anualmente pelo IBGE desde 1981. Essa pesquisa investiga diversas características da população brasileira, tais como educação, trabalho, rendimento, composição domiciliar e fecundidade. Em quase todos os anos, ocorre também a investigação de um tema suplementar - educação, saúde, qualificação profissional e segurança alimentar, entre outros. A amostra da PNAD 2013 cobria 148.697 domicílios com 362.555 indivíduos.

### Microdados

Até 1990, havia um único arquivo por ano, contendo os microdados referentes a domicílios e pessoas. A partir de 1992, as informações de domicílios e pessoas foram separadas em dois arquivos distintos.

O IBGE disponibiliza gratuitamente para download os microdados e toda a documentação para todas as PNADs desde 2001 [neste link](https://www.ibge.gov.br/estatisticas/sociais/populacao/9127-pesquisa-nacional-por-amostra-de-domicilios.html?=&t=microdados). Para obter informações a respeito de como adquirir os microdados para outros anos, [clique aqui](https://loja.ibge.gov.br/catalogsearch/result/?q=pnad).

Diversas alterações metodológicas foram realizadas pelo IBGE ao longo dos anos. Desta forma, a mesma informação pode não estar disponível em todos os anos e/ou pode não ter sido recolhida da mesma forma. Especificamente, houve uma grande reformulação da PNAD em 1992, na qual se destacam a alteração do conceito de trabalho e a adoção de um novo formato do questionário, inclusive com alterações de nomes de variáveis.

O Data Zoom disponibiliza duas opções para compatibilizar as variáveis ao longo do tempo. A primeira opção busca adaptar as décadas de 1990 e 2000 aos anos 1980. Entre outras implicações, diversas variáveis existentes a partir de 1992 são excluídas no processo (todas as variáveis relacionadas a trabalho infantil, por exemplo), pois não existiam antes desse ano. Neste caso, as variáveis da base de dados compatibilizada para os anos 1980 não possuem os nomes sugeridos pelo dicionário original, sendo um novo dicionário disponibilizado para download.

A segunda opção de compatibilização procura padronizar as variáveis somente entre 1992 e 2012. Como houve poucas alterações no período, foram mantidas com o nome original todas as variáveis que não sofreram grandes modificações. Outro dicionário, indicando as variáveis existentes nesta base compatibilizada para os anos 1990, é disponibilizado para download. O documento [Compatibilização das PNADs](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/compatibilizacao.pdf) explica todos os procedimentos adotados nas duas opções de compatibilização do programa.

### Arquivos de apoio

  - [Microdados e documentação](https://www.ibge.gov.br/estatisticas/sociais/populacao/9127-pesquisa-nacional-por-amostra-de-domicilios.html?=&t=microdados)
  - [Dicionário compatibilizado](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_compatibilizado.xlsx)

<details>
<summary> Em português: </summary>

  - [Compatibilização das PNADs](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/compatibilizacao.pdf)
  - Dicionários anos 1980
    - [1981](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1981.pdf), [1982](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1982.pdf), [1983](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1983.pdf), [1984](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1984.pdf), [1985](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1985.pdf), [1986](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1986.pdf), [1987](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1987.pdf), [1988](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1988.pdf), [1989](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1989.pdf)
  - Dicionários anos 1990
    - [1990](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1990.pdf), [1992-1995 (Domicílios)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1992_1995_dom.pdf), [1992-1995 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1992_1995_pess.pdf), [1996 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1996_pess.pdf), [1996-1997 (Domicílios)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1996_1997_dom.pdf), [1997 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1997_pess.pdf), [1998 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1998_pess.pdf), [1998-1999 (Domicílios)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1998_1999_dom.pdf), [1999 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1999_pess.pdf)
  - [Dicionário 2000-2012 (Domicílios)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_2000s_dom.xlsx)
  - [Dicionário 2000-2012 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_2000s_pess.xlsx)  
  
</details>

<details>
<summary> Em inglês: </summary>

  - [Compatibilização das PNADs](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/compatibilizacao_en.pdf)
  - Dicionários anos 1980
    - [1981](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1981_en.pdf), [1982](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1982_en.pdf), [1983](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1983_en.pdf), [1984](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1984_en.pdf), [1985](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1985_en.pdf), [1986](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1986_en.pdf), [1987](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1987_en.pdf), [1988](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1988_en.pdf), [1989](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1989_en.pdf)
  - Dicionários anos 1990
    - [1990](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1990_en.pdf), [1992-1995 (Domicílios)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1992_1995_dom_en.pdf), [1992-1995 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1992_1995_pess_en.pdf), [1996 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1996_pess_en.pdf), [1996-1997 (Domicílios)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1996_1997_dom_en.pdf), [1997 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1997_pess_en.pdf), [1998 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1998_pess_en.pdf), [1998-1999 (Domicílios)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1998_1999_dom_en.pdf), [1999 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_1999_pess_en.pdf)
  - [Dicionário 2000-2012 (Domicílios)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_2000s_dom_en.xlsx)
  - [Dicionário 2000-2012 (Pessoas)](https://raw.githubusercontent.com/datazoompuc/datazoom_social_stata/master/docs/PNAD/dicionario_2000s_pess_en.xlsx)  
  
</details>


